---
- name: Install Apache Tomcat server
  hosts: tomcat
  become: true
  tasks:
    - name: Update apt package
      #command: apt-get update
      apt:
        update_cache: yes

    - name: Install Java21
      apt:
        name: openjdk-21-jdk
        state: present

    - name: Download Tomcat11
      get_url:
        url: "https://dlcdn.apache.org/tomcat/tomcat-11/v11.0.0-M17/bin/apache-tomcat-11.0.0-M17.tar.gz"
        dest: "/tmp/apache-tomcat-11.0.0-M17.tar.gz"

    - name: Extract Tomcat11
      unarchive:
        src: "/tmp/apache-tomcat-11.0.0-M17.tar.gz"
        dest: "/opt"
        remote_src: yes

    - name: Set permissions for Tomcat directory
      file:
        path: "/opt/apache-tomcat-11.0.0-M17"
        owner: "{{ tomcat_user }}"
        group: "{{ tomcat_group }}"
        mode: "0755"

    - name: Start Tomcat service
      shell: "/opt/apache-tomcat-11.0.0-M17/bin/startup.sh"
      ignore_errors: true

    - name: Wait for Tomcat to start
      wait_for:
         host: localhost
         port: 8080
         state: started
            